### ISSUE TITLE
Migrate to withTracker from createContainer

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#95] opened 2017-11-03 20:30 UTC
Damn kids, quit moving around the signs on my front lawn!

**Comment by tomscholz** [comment] 2017-11-03 20:34
Duplicate of #91

**Comment by cleverbeagle** [comment] 2017-11-03 20:38
@tomscholz https://www.youtube.com/watch?v=nCTr-4CoeVs

**Closed** 2017-11-13 14:36 UTC
Labels: refactor
